apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetesdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetesdemo
  template:
    metadata:
      labels:
        app: kubernetesdemo
    spec:
      containers:
        - image: "kubernetesdemo12.azurecr.io/kubernetesdemo:1027-20220401.4"
          imagePullPolicy: IfNotPresent
          name: kubernetesdemo
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
          - name: ASPNETCORE_Kestrel__Certificates__Default__Password
            valueFrom:
              secretKeyRef:
                name: kubernetesbase64pfxfilepassword
                key: password
          - name: ASPNETCORE_URLS
            value: "https://+;http://+;"
          - name: APIURL
            value: "http://kubernetesdemoapilb.default"            
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetesdemo
spec:
  type: NodePort
  ports:
  - name: http-port
    port: 80
    targetPort: 80
  - name: https-port
    port: 443
    targetPort: 443
  selector:
    app: kubernetesdemo
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetesdemolb
spec:
  type: LoadBalancer
  ports:
  - name: http-port
    port: 80
  - name: https-port
    port: 443
  selector:
    app: kubernetesdemo  