apiVersion: apps/v1
kind: Deployment
metadata:
  name: elemetnslicensinghttps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elemetnslicensinghttps
  template:
    metadata:
      labels:
        app: elemetnslicensinghttps
    spec:
      containers:
        - image: "elemetnslicensinghttps"
          imagePullPolicy: Always
          name: elemetnslicensinghttps
          ports:
            - containerPort: 80