appName: kubernetesdemoapi
replicaCount: 1
volume:
    volumeName: elementshttps-cert-volume
    secretName: elementshttps-cert
    volumeMountPath: /elements/elementshttps-cert
    pfxFileName: elementshttps.pfx


loadbalancerName: kubernetesdemoapilb
httpPort: 80
httpsPort: 443
sslCertPasswordSecretName: kubernetesbase64pfxfilepassword
aspnetCoreUrls: "http://+;https://+;"

container:
    imageName: kubernetesdemo12.azurecr.io/kubernetesdemoapi:1026-20220401.3
    containerName: kubernetesdemoapi
    imagePullSecret: kubedemopappregistry-secret
    imagePullPolicy: IfNotPresent
    httpPort: 80
    httpsPort: 443    